-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 17:35:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`postal_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`postal_code` ;

CREATE TABLE IF NOT EXISTS `mydb`.`postal_code` (
  `ps_val` INT NOT NULL AUTO_INCREMENT,
  `suburb_name` VARCHAR(45) NOT NULL,
  `post_code` INT NOT NULL,
  PRIMARY KEY (`ps_val`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historical_building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`historical_building` ;

CREATE TABLE IF NOT EXISTS `mydb`.`historical_building` (
  `hist_id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DOUBLE(8,6) NOT NULL,
  `longitude` DOUBLE(9,6) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `image_url` VARCHAR(120) NULL,
  `description` LONGTEXT NULL,
  `address` VARCHAR(120) NOT NULL,
  `summary` LONGTEXT NULL,
  `postal_code_ps_val` INT NOT NULL,
  PRIMARY KEY (`hist_id`, `postal_code_ps_val`),
  INDEX `fk_historical_building_postal_code1_idx` (`postal_code_ps_val` ASC) VISIBLE,
  CONSTRAINT `fk_historical_building_postal_code1`
    FOREIGN KEY (`postal_code_ps_val`)
    REFERENCES `mydb`.`postal_code` (`ps_val`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crashes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crashes` (
  `accident_id` INT NOT NULL,
  `ps_val` INT NOT NULL,
  `latitude` DOUBLE(8,6) NOT NULL,
  `longitude` DOUBLE(9,6) NOT NULL,
  `node_type` VARCHAR(45) NOT NULL,
  `address` VARCHAR(120) NULL,
  `postal_code_ps_val` INT NOT NULL,
  PRIMARY KEY (`accident_id`, `postal_code_ps_val`),
  INDEX `fk_crashes_postal_code1_idx` (`postal_code_ps_val` ASC) VISIBLE,
  CONSTRAINT `fk_crashes_postal_code1`
    FOREIGN KEY (`postal_code_ps_val`)
    REFERENCES `mydb`.`postal_code` (`ps_val`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`point_of_interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`point_of_interest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`point_of_interest` (
  `poi_id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DOUBLE(8,6) NOT NULL,
  `longitude` DOUBLE(9,6) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  `category_cat_id` INT NOT NULL,
  `postal_code_ps_val` INT NOT NULL,
  PRIMARY KEY (`poi_id`, `category_cat_id`, `postal_code_ps_val`),
  INDEX `fk_point_of_interest_category1_idx` (`category_cat_id` ASC) VISIBLE,
  INDEX `fk_point_of_interest_postal_code1_idx` (`postal_code_ps_val` ASC) VISIBLE,
  CONSTRAINT `fk_point_of_interest_category1`
    FOREIGN KEY (`category_cat_id`)
    REFERENCES `mydb`.`category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_point_of_interest_postal_code1`
    FOREIGN KEY (`postal_code_ps_val`)
    REFERENCES `mydb`.`postal_code` (`ps_val`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
